force-app/main/default/objects/Academic_Year__c/Academic_Year__c.object-meta.xml
<CustomObject>
    <label>Academic Year</label>
    <nameField>
        <displayFormat>AY-{000}</displayFormat>
        <label>S.No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academic Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Academic_Year__c/fields/Academic_Year__c.field-meta.xml
<CustomField>
    <fullName>Academic_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Academic Year</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Academic Years</relationshipLabel>
    <relationshipName>Academic_Years</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Academic_Year__c/fields/From_Month__c.field-meta.xml
<CustomField>
    <fullName>From_Month__c</fullName>
    <label>From Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Jan</fullName>
            </value>
            <value>
                <fullName>Feb</fullName>
            </value>
            <value>
                <fullName>Mar</fullName>
            </value>
            <value>
                <fullName>Apr</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>Aug</fullName>
            </value>
            <value>
                <fullName>Sep</fullName>
            </value>
            <value>
                <fullName>Oct</fullName>
            </value>
            <value>
                <fullName>Nov</fullName>
            </value>
            <value>
                <fullName>Dec</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Academic_Year__c/fields/From_Year__c.field-meta.xml
<CustomField>
    <fullName>From_Year__c</fullName>
    <label>From Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>2001</fullName>
            </value>
            <value>
                <fullName>2002</fullName>
            </value>
            <value>
                <fullName>2003</fullName>
            </value>
            <value>
                <fullName>2004</fullName>
            </value>
            <value>
                <fullName>2005</fullName>
            </value>
            <value>
                <fullName>2006</fullName>
            </value>
            <value>
                <fullName>2007</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2009</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>1990</fullName>
            </value>
            <value>
                <fullName>1991</fullName>
            </value>
            <value>
                <fullName>1992</fullName>
            </value>
            <value>
                <fullName>1993</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Academic_Year__c/fields/To_Month__c.field-meta.xml
<CustomField>
    <fullName>To_Month__c</fullName>
    <label>To Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Jan</fullName>
            </value>
            <value>
                <fullName>Feb</fullName>
            </value>
            <value>
                <fullName>Mar</fullName>
            </value>
            <value>
                <fullName>Apr</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>Aug</fullName>
            </value>
            <value>
                <fullName>Sep</fullName>
            </value>
            <value>
                <fullName>Oct</fullName>
            </value>
            <value>
                <fullName>Nov</fullName>
            </value>
            <value>
                <fullName>Dec</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Academic_Year__c/fields/To_Year__c.field-meta.xml
<CustomField>
    <fullName>To_Year__c</fullName>
    <label>To Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>2001</fullName>
            </value>
            <value>
                <fullName>2002</fullName>
            </value>
            <value>
                <fullName>2003</fullName>
            </value>
            <value>
                <fullName>2004</fullName>
            </value>
            <value>
                <fullName>2005</fullName>
            </value>
            <value>
                <fullName>2006</fullName>
            </value>
            <value>
                <fullName>2007</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2009</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>1990</fullName>
            </value>
            <value>
                <fullName>1991</fullName>
            </value>
            <value>
                <fullName>1992</fullName>
            </value>
            <value>
                <fullName>1993</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Lookup.cls
public without sharing class Lookup {
  @AuraEnabled(cacheable=true)
  public static List<sObject> search(
    String searchTerm,
    string myObject,
    String filter
  ) {
    String myQuery = null;
    if (myObject == 'Academic_Year__c') {
      myQuery =
        'Select Id, Name, From_Year__c, From_Month__c, To_Year__c, To_Month__c from ' +
        myObject +
        ' Where Name Like  \'%' +
        searchTerm +
        '%\'';
    } else if (filter != null && filter != '') {
      myQuery =
        'Select Id, Name from ' +
        myObject +
        ' Where Name Like  \'%' +
        searchTerm +
        '%\' AND ' +
        filter +
        ' LIMIT  5';
    } else {
      myQuery =
        'Select Id, Name from ' +
        myObject +
        ' Where Name Like  \'%' +
        searchTerm +
        '%\' LIMIT  5';
    }
    List<sObject> lookUpList = database.query(myQuery);
    return lookUpList;
  }

  @AuraEnabled
  public static String deleteRecord(string myObject, List<String> recordId) {
    try {
      List<SObject> recordList = new List<SObject>();
      String query = 'SELECT Id FROM ' + myObject + ' WHERE Id IN : recordId';
      recordList = Database.query(query);
      if (recordList.size() < 1) {
        return 'Error: No data Found!';
      } else {
        delete recordList;
        return 'Success';
      }
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}